services:
  db:
    image: postgres:14.6
    profiles: ["db", "cef"]
    environment:
      POSTGRES_USER: controlefect
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ctrefc
      #POSTGRES_SCHEMA: controlefect
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backnet

  app:
    image: cef-backend-dev:latest
    profiles: ["app", "cef"]
    ports:
      - "8080:8080"
    environment:
      url: jdbc:postgresql://db:5432/ctrefc
      user: controlefect
      pass: 123456
      schema: controlefect
      bucket: awue1athcef-dev
      region: us-east-1
    networks:
      - backnet

volumes:
  db-data:

networks:
  backnet: